// -*- C++ -*-
// Copyright (C) Dmitry Igrishin
// For conditions of distribution and use, see files LICENSE.txt or pgfe.hpp

#include "dmitigr/pgfe/exceptions.hpp"

namespace dmitigr::pgfe {

DMITIGR_PGFE_INLINE void throw_server_exception(std::shared_ptr<Error> error)
{
  if (!error)
    return;

  const Server_errc errc{error->code().value()};
  switch (errc) {
  case Server_errc::c00_successful_completion:
    throw c00_Successful_completion{std::move(error)};
  case Server_errc::c01_warning:
    throw c01_Warning{std::move(error)};
  case Server_errc::c01_dynamic_result_sets_returned:
    throw c01_Dynamic_result_sets_returned{std::move(error)};
  case Server_errc::c01_implicit_zero_bit_padding:
    throw c01_Implicit_zero_bit_padding{std::move(error)};
  case Server_errc::c01_null_value_eliminated_in_set_function:
    throw c01_Null_value_eliminated_in_set_function{std::move(error)};
  case Server_errc::c01_privilege_not_granted:
    throw c01_Privilege_not_granted{std::move(error)};
  case Server_errc::c01_privilege_not_revoked:
    throw c01_Privilege_not_revoked{std::move(error)};
  case Server_errc::c01_string_data_right_truncation:
    throw c01_String_data_right_truncation{std::move(error)};
  case Server_errc::c01_deprecated_feature:
    throw c01_Deprecated_feature{std::move(error)};
  case Server_errc::c02_no_data:
    throw c02_No_data{std::move(error)};
  case Server_errc::c02_no_additional_dynamic_result_sets_returned:
    throw c02_No_additional_dynamic_result_sets_returned{std::move(error)};
  case Server_errc::c03_sql_statement_not_yet_complete:
    throw c03_Sql_statement_not_yet_complete{std::move(error)};
  case Server_errc::c08_connection_exception:
    throw c08_Connection_exception{std::move(error)};
  case Server_errc::c08_connection_does_not_exist:
    throw c08_Connection_does_not_exist{std::move(error)};
  case Server_errc::c08_connection_failure:
    throw c08_Connection_failure{std::move(error)};
  case Server_errc::c08_sqlclient_unable_to_establish_sqlconnection:
    throw c08_Sqlclient_unable_to_establish_sqlconnection{std::move(error)};
  case Server_errc::c08_sqlserver_rejected_establishment_of_sqlconnection:
    throw c08_Sqlserver_rejected_establishment_of_sqlconnection{std::move(error)};
  case Server_errc::c08_transaction_resolution_unknown:
    throw c08_Transaction_resolution_unknown{std::move(error)};
  case Server_errc::c08_protocol_violation:
    throw c08_Protocol_violation{std::move(error)};
  case Server_errc::c09_triggered_action_exception:
    throw c09_Triggered_action_exception{std::move(error)};
  case Server_errc::c0a_feature_not_supported:
    throw c0a_Feature_not_supported{std::move(error)};
  case Server_errc::c0b_invalid_transaction_initiation:
    throw c0b_Invalid_transaction_initiation{std::move(error)};
  case Server_errc::c0f_locator_exception:
    throw c0f_Locator_exception{std::move(error)};
  case Server_errc::c0f_invalid_locator_specification:
    throw c0f_Invalid_locator_specification{std::move(error)};
  case Server_errc::c0l_invalid_grantor:
    throw c0l_Invalid_grantor{std::move(error)};
  case Server_errc::c0l_invalid_grant_operation:
    throw c0l_Invalid_grant_operation{std::move(error)};
  case Server_errc::c0p_invalid_role_specification:
    throw c0p_Invalid_role_specification{std::move(error)};
  case Server_errc::c0z_diagnostics_exception:
    throw c0z_Diagnostics_exception{std::move(error)};
  case Server_errc::c0z_stacked_diagnostics_accessed_without_active_handler:
    throw c0z_Stacked_diagnostics_accessed_without_active_handler{std::move(error)};
  case Server_errc::c20_case_not_found:
    throw c20_Case_not_found{std::move(error)};
  case Server_errc::c21_cardinality_violation:
    throw c21_Cardinality_violation{std::move(error)};
  case Server_errc::c22_data_exception:
    throw c22_Data_exception{std::move(error)};
  case Server_errc::c22_array_subscript_error:
    throw c22_Array_subscript_error{std::move(error)};
  case Server_errc::c22_character_not_in_repertoire:
    throw c22_Character_not_in_repertoire{std::move(error)};
  case Server_errc::c22_datetime_field_overflow:
    throw c22_Datetime_field_overflow{std::move(error)};
  case Server_errc::c22_division_by_zero:
    throw c22_Division_by_zero{std::move(error)};
  case Server_errc::c22_error_in_assignment:
    throw c22_Error_in_assignment{std::move(error)};
  case Server_errc::c22_escape_character_conflict:
    throw c22_Escape_character_conflict{std::move(error)};
  case Server_errc::c22_indicator_overflow:
    throw c22_Indicator_overflow{std::move(error)};
  case Server_errc::c22_interval_field_overflow:
    throw c22_Interval_field_overflow{std::move(error)};
  case Server_errc::c22_invalid_argument_for_logarithm:
    throw c22_Invalid_argument_for_logarithm{std::move(error)};
  case Server_errc::c22_invalid_argument_for_ntile_function:
    throw c22_Invalid_argument_for_ntile_function{std::move(error)};
  case Server_errc::c22_invalid_argument_for_nth_value_function:
    throw c22_Invalid_argument_for_nth_value_function{std::move(error)};
  case Server_errc::c22_invalid_argument_for_power_function:
    throw c22_Invalid_argument_for_power_function{std::move(error)};
  case Server_errc::c22_invalid_argument_for_width_bucket_function:
    throw c22_Invalid_argument_for_width_bucket_function{std::move(error)};
  case Server_errc::c22_invalid_character_value_for_cast:
    throw c22_Invalid_character_value_for_cast{std::move(error)};
  case Server_errc::c22_invalid_datetime_format:
    throw c22_Invalid_datetime_format{std::move(error)};
  case Server_errc::c22_invalid_escape_character:
    throw c22_Invalid_escape_character{std::move(error)};
  case Server_errc::c22_invalid_escape_octet:
    throw c22_Invalid_escape_octet{std::move(error)};
  case Server_errc::c22_invalid_escape_sequence:
    throw c22_Invalid_escape_sequence{std::move(error)};
  case Server_errc::c22_nonstandard_use_of_escape_character:
    throw c22_Nonstandard_use_of_escape_character{std::move(error)};
  case Server_errc::c22_invalid_indicator_parameter_value:
    throw c22_Invalid_indicator_parameter_value{std::move(error)};
  case Server_errc::c22_invalid_parameter_value:
    throw c22_Invalid_parameter_value{std::move(error)};
  case Server_errc::c22_invalid_preceding_following_size:
    throw c22_Invalid_preceding_following_size{std::move(error)};
  case Server_errc::c22_invalid_regular_expression:
    throw c22_Invalid_regular_expression{std::move(error)};
  case Server_errc::c22_invalid_row_count_in_limit_clause:
    throw c22_Invalid_row_count_in_limit_clause{std::move(error)};
  case Server_errc::c22_invalid_row_count_in_result_offset_clause:
    throw c22_Invalid_row_count_in_result_offset_clause{std::move(error)};
  case Server_errc::c22_invalid_tablesample_argument:
    throw c22_Invalid_tablesample_argument{std::move(error)};
  case Server_errc::c22_invalid_tablesample_repeat:
    throw c22_Invalid_tablesample_repeat{std::move(error)};
  case Server_errc::c22_invalid_time_zone_displacement_value:
    throw c22_Invalid_time_zone_displacement_value{std::move(error)};
  case Server_errc::c22_invalid_use_of_escape_character:
    throw c22_Invalid_use_of_escape_character{std::move(error)};
  case Server_errc::c22_most_specific_type_mismatch:
    throw c22_Most_specific_type_mismatch{std::move(error)};
  case Server_errc::c22_null_value_not_allowed:
    throw c22_Null_value_not_allowed{std::move(error)};
  case Server_errc::c22_null_value_no_indicator_parameter:
    throw c22_Null_value_no_indicator_parameter{std::move(error)};
  case Server_errc::c22_numeric_value_out_of_range:
    throw c22_Numeric_value_out_of_range{std::move(error)};
  case Server_errc::c22_sequence_generator_limit_exceeded:
    throw c22_Sequence_generator_limit_exceeded{std::move(error)};
  case Server_errc::c22_string_data_length_mismatch:
    throw c22_String_data_length_mismatch{std::move(error)};
  case Server_errc::c22_string_data_right_truncation:
    throw c22_String_data_right_truncation{std::move(error)};
  case Server_errc::c22_substring_error:
    throw c22_Substring_error{std::move(error)};
  case Server_errc::c22_trim_error:
    throw c22_Trim_error{std::move(error)};
  case Server_errc::c22_unterminated_c_string:
    throw c22_Unterminated_c_string{std::move(error)};
  case Server_errc::c22_zero_length_character_string:
    throw c22_Zero_length_character_string{std::move(error)};
  case Server_errc::c22_floating_point_exception:
    throw c22_Floating_point_exception{std::move(error)};
  case Server_errc::c22_invalid_text_representation:
    throw c22_Invalid_text_representation{std::move(error)};
  case Server_errc::c22_invalid_binary_representation:
    throw c22_Invalid_binary_representation{std::move(error)};
  case Server_errc::c22_bad_copy_file_format:
    throw c22_Bad_copy_file_format{std::move(error)};
  case Server_errc::c22_untranslatable_character:
    throw c22_Untranslatable_character{std::move(error)};
  case Server_errc::c22_not_an_xml_document:
    throw c22_Not_an_xml_document{std::move(error)};
  case Server_errc::c22_invalid_xml_document:
    throw c22_Invalid_xml_document{std::move(error)};
  case Server_errc::c22_invalid_xml_content:
    throw c22_Invalid_xml_content{std::move(error)};
  case Server_errc::c22_invalid_xml_comment:
    throw c22_Invalid_xml_comment{std::move(error)};
  case Server_errc::c22_invalid_xml_processing_instruction:
    throw c22_Invalid_xml_processing_instruction{std::move(error)};
  case Server_errc::c22_duplicate_json_object_key_value:
    throw c22_Duplicate_json_object_key_value{std::move(error)};
  case Server_errc::c22_invalid_argument_for_sql_json_datetime_function:
    throw c22_Invalid_argument_for_sql_json_datetime_function{std::move(error)};
  case Server_errc::c22_invalid_json_text:
    throw c22_Invalid_json_text{std::move(error)};
  case Server_errc::c22_invalid_json_subscript:
    throw c22_Invalid_json_subscript{std::move(error)};
  case Server_errc::c22_more_than_one_json_item:
    throw c22_More_than_one_json_item{std::move(error)};
  case Server_errc::c22_no_json_item:
    throw c22_No_json_item{std::move(error)};
  case Server_errc::c22_non_numeric_json_item:
    throw c22_Non_numeric_json_item{std::move(error)};
  case Server_errc::c22_non_unique_keys_in_json_object:
    throw c22_Non_unique_keys_in_json_object{std::move(error)};
  case Server_errc::c22_singleton_json_item_required:
    throw c22_Singleton_json_item_required{std::move(error)};
  case Server_errc::c22_json_array_not_found:
    throw c22_Json_array_not_found{std::move(error)};
  case Server_errc::c22_json_member_not_found:
    throw c22_Json_member_not_found{std::move(error)};
  case Server_errc::c22_json_number_not_found:
    throw c22_Json_number_not_found{std::move(error)};
  case Server_errc::c22_object_not_found:
    throw c22_Object_not_found{std::move(error)};
  case Server_errc::c22_too_many_json_array_elements:
    throw c22_Too_many_json_array_elements{std::move(error)};
  case Server_errc::c22_too_many_json_object_members:
    throw c22_Too_many_json_object_members{std::move(error)};
  case Server_errc::c22_json_scalar_required:
    throw c22_Json_scalar_required{std::move(error)};
  case Server_errc::c23_integrity_constraint_violation:
    throw c23_Integrity_constraint_violation{std::move(error)};
  case Server_errc::c23_restrict_violation:
    throw c23_Restrict_violation{std::move(error)};
  case Server_errc::c23_not_null_violation:
    throw c23_Not_null_violation{std::move(error)};
  case Server_errc::c23_foreign_key_violation:
    throw c23_Foreign_key_violation{std::move(error)};
  case Server_errc::c23_unique_violation:
    throw c23_Unique_violation{std::move(error)};
  case Server_errc::c23_check_violation:
    throw c23_Check_violation{std::move(error)};
  case Server_errc::c23_exclusion_violation:
    throw c23_Exclusion_violation{std::move(error)};
  case Server_errc::c24_invalid_cursor_state:
    throw c24_Invalid_cursor_state{std::move(error)};
  case Server_errc::c25_invalid_transaction_state:
    throw c25_Invalid_transaction_state{std::move(error)};
  case Server_errc::c25_active_sql_transaction:
    throw c25_Active_sql_transaction{std::move(error)};
  case Server_errc::c25_branch_transaction_already_active:
    throw c25_Branch_transaction_already_active{std::move(error)};
  case Server_errc::c25_held_cursor_requires_same_isolation_level:
    throw c25_Held_cursor_requires_same_isolation_level{std::move(error)};
  case Server_errc::c25_inappropriate_access_mode_for_branch_transaction:
    throw c25_Inappropriate_access_mode_for_branch_transaction{std::move(error)};
  case Server_errc::c25_inappropriate_isolation_level_for_branch_transaction:
    throw c25_Inappropriate_isolation_level_for_branch_transaction{std::move(error)};
  case Server_errc::c25_no_active_sql_transaction_for_branch_transaction:
    throw c25_No_active_sql_transaction_for_branch_transaction{std::move(error)};
  case Server_errc::c25_read_only_sql_transaction:
    throw c25_Read_only_sql_transaction{std::move(error)};
  case Server_errc::c25_schema_and_data_statement_mixing_not_supported:
    throw c25_Schema_and_data_statement_mixing_not_supported{std::move(error)};
  case Server_errc::c25_no_active_sql_transaction:
    throw c25_No_active_sql_transaction{std::move(error)};
  case Server_errc::c25_in_failed_sql_transaction:
    throw c25_In_failed_sql_transaction{std::move(error)};
  case Server_errc::c25_idle_in_transaction_session_timeout:
    throw c25_Idle_in_transaction_session_timeout{std::move(error)};
  case Server_errc::c26_invalid_sql_statement_name:
    throw c26_Invalid_sql_statement_name{std::move(error)};
  case Server_errc::c27_triggered_data_change_violation:
    throw c27_Triggered_data_change_violation{std::move(error)};
  case Server_errc::c28_invalid_authorization_specification:
    throw c28_Invalid_authorization_specification{std::move(error)};
  case Server_errc::c28_invalid_password:
    throw c28_Invalid_password{std::move(error)};
  case Server_errc::c2b_dependent_privilege_descriptors_still_exist:
    throw c2b_Dependent_privilege_descriptors_still_exist{std::move(error)};
  case Server_errc::c2b_dependent_objects_still_exist:
    throw c2b_Dependent_objects_still_exist{std::move(error)};
  case Server_errc::c2d_invalid_transaction_termination:
    throw c2d_Invalid_transaction_termination{std::move(error)};
  case Server_errc::c2f_sql_routine_exception:
    throw c2f_Sql_routine_exception{std::move(error)};
  case Server_errc::c2f_function_executed_no_return_statement:
    throw c2f_Function_executed_no_return_statement{std::move(error)};
  case Server_errc::c2f_modifying_sql_data_not_permitted:
    throw c2f_Modifying_sql_data_not_permitted{std::move(error)};
  case Server_errc::c2f_prohibited_sql_statement_attempted:
    throw c2f_Prohibited_sql_statement_attempted{std::move(error)};
  case Server_errc::c2f_reading_sql_data_not_permitted:
    throw c2f_Reading_sql_data_not_permitted{std::move(error)};
  case Server_errc::c34_invalid_cursor_name:
    throw c34_Invalid_cursor_name{std::move(error)};
  case Server_errc::c38_external_routine_exception:
    throw c38_External_routine_exception{std::move(error)};
  case Server_errc::c38_containing_sql_not_permitted:
    throw c38_Containing_sql_not_permitted{std::move(error)};
  case Server_errc::c38_modifying_sql_data_not_permitted:
    throw c38_Modifying_sql_data_not_permitted{std::move(error)};
  case Server_errc::c38_prohibited_sql_statement_attempted:
    throw c38_Prohibited_sql_statement_attempted{std::move(error)};
  case Server_errc::c38_reading_sql_data_not_permitted:
    throw c38_Reading_sql_data_not_permitted{std::move(error)};
  case Server_errc::c39_external_routine_invocation_exception:
    throw c39_External_routine_invocation_exception{std::move(error)};
  case Server_errc::c39_invalid_sqlstate_returned:
    throw c39_Invalid_sqlstate_returned{std::move(error)};
  case Server_errc::c39_null_value_not_allowed:
    throw c39_Null_value_not_allowed{std::move(error)};
  case Server_errc::c39_trigger_protocol_violated:
    throw c39_Trigger_protocol_violated{std::move(error)};
  case Server_errc::c39_srf_protocol_violated:
    throw c39_Srf_protocol_violated{std::move(error)};
  case Server_errc::c39_event_trigger_protocol_violated:
    throw c39_Event_trigger_protocol_violated{std::move(error)};
  case Server_errc::c3b_savepoint_exception:
    throw c3b_Savepoint_exception{std::move(error)};
  case Server_errc::c3b_invalid_savepoint_specification:
    throw c3b_Invalid_savepoint_specification{std::move(error)};
  case Server_errc::c3d_invalid_catalog_name:
    throw c3d_Invalid_catalog_name{std::move(error)};
  case Server_errc::c3f_invalid_schema_name:
    throw c3f_Invalid_schema_name{std::move(error)};
  case Server_errc::c40_transaction_rollback:
    throw c40_Transaction_rollback{std::move(error)};
  case Server_errc::c40_transaction_integrity_constraint_violation:
    throw c40_Transaction_integrity_constraint_violation{std::move(error)};
  case Server_errc::c40_serialization_failure:
    throw c40_Serialization_failure{std::move(error)};
  case Server_errc::c40_statement_completion_unknown:
    throw c40_Statement_completion_unknown{std::move(error)};
  case Server_errc::c40_deadlock_detected:
    throw c40_Deadlock_detected{std::move(error)};
  case Server_errc::c42_syntax_error_or_access_rule_violation:
    throw c42_Syntax_error_or_access_rule_violation{std::move(error)};
  case Server_errc::c42_syntax_error:
    throw c42_Syntax_error{std::move(error)};
  case Server_errc::c42_insufficient_privilege:
    throw c42_Insufficient_privilege{std::move(error)};
  case Server_errc::c42_cannot_coerce:
    throw c42_Cannot_coerce{std::move(error)};
  case Server_errc::c42_grouping_error:
    throw c42_Grouping_error{std::move(error)};
  case Server_errc::c42_windowing_error:
    throw c42_Windowing_error{std::move(error)};
  case Server_errc::c42_invalid_recursion:
    throw c42_Invalid_recursion{std::move(error)};
  case Server_errc::c42_invalid_foreign_key:
    throw c42_Invalid_foreign_key{std::move(error)};
  case Server_errc::c42_invalid_name:
    throw c42_Invalid_name{std::move(error)};
  case Server_errc::c42_name_too_long:
    throw c42_Name_too_long{std::move(error)};
  case Server_errc::c42_reserved_name:
    throw c42_Reserved_name{std::move(error)};
  case Server_errc::c42_datatype_mismatch:
    throw c42_Datatype_mismatch{std::move(error)};
  case Server_errc::c42_indeterminate_datatype:
    throw c42_Indeterminate_datatype{std::move(error)};
  case Server_errc::c42_collation_mismatch:
    throw c42_Collation_mismatch{std::move(error)};
  case Server_errc::c42_indeterminate_collation:
    throw c42_Indeterminate_collation{std::move(error)};
  case Server_errc::c42_wrong_object_type:
    throw c42_Wrong_object_type{std::move(error)};
  case Server_errc::c42_generated_always:
    throw c42_Generated_always{std::move(error)};
  case Server_errc::c42_undefined_column:
    throw c42_Undefined_column{std::move(error)};
  case Server_errc::c42_undefined_function:
    throw c42_Undefined_function{std::move(error)};
  case Server_errc::c42_undefined_table:
    throw c42_Undefined_table{std::move(error)};
  case Server_errc::c42_undefined_parameter:
    throw c42_Undefined_parameter{std::move(error)};
  case Server_errc::c42_undefined_object:
    throw c42_Undefined_object{std::move(error)};
  case Server_errc::c42_duplicate_column:
    throw c42_Duplicate_column{std::move(error)};
  case Server_errc::c42_duplicate_cursor:
    throw c42_Duplicate_cursor{std::move(error)};
  case Server_errc::c42_duplicate_database:
    throw c42_Duplicate_database{std::move(error)};
  case Server_errc::c42_duplicate_function:
    throw c42_Duplicate_function{std::move(error)};
  case Server_errc::c42_duplicate_prepared_statement:
    throw c42_Duplicate_prepared_statement{std::move(error)};
  case Server_errc::c42_duplicate_schema:
    throw c42_Duplicate_schema{std::move(error)};
  case Server_errc::c42_duplicate_table:
    throw c42_Duplicate_table{std::move(error)};
  case Server_errc::c42_duplicate_alias:
    throw c42_Duplicate_alias{std::move(error)};
  case Server_errc::c42_duplicate_object:
    throw c42_Duplicate_object{std::move(error)};
  case Server_errc::c42_ambiguous_column:
    throw c42_Ambiguous_column{std::move(error)};
  case Server_errc::c42_ambiguous_function:
    throw c42_Ambiguous_function{std::move(error)};
  case Server_errc::c42_ambiguous_parameter:
    throw c42_Ambiguous_parameter{std::move(error)};
  case Server_errc::c42_ambiguous_alias:
    throw c42_Ambiguous_alias{std::move(error)};
  case Server_errc::c42_invalid_column_reference:
    throw c42_Invalid_column_reference{std::move(error)};
  case Server_errc::c42_invalid_column_definition:
    throw c42_Invalid_column_definition{std::move(error)};
  case Server_errc::c42_invalid_cursor_definition:
    throw c42_Invalid_cursor_definition{std::move(error)};
  case Server_errc::c42_invalid_database_definition:
    throw c42_Invalid_database_definition{std::move(error)};
  case Server_errc::c42_invalid_function_definition:
    throw c42_Invalid_function_definition{std::move(error)};
  case Server_errc::c42_invalid_prepared_statement_definition:
    throw c42_Invalid_prepared_statement_definition{std::move(error)};
  case Server_errc::c42_invalid_schema_definition:
    throw c42_Invalid_schema_definition{std::move(error)};
  case Server_errc::c42_invalid_table_definition:
    throw c42_Invalid_table_definition{std::move(error)};
  case Server_errc::c42_invalid_object_definition:
    throw c42_Invalid_object_definition{std::move(error)};
  case Server_errc::c44_with_check_option_violation:
    throw c44_With_check_option_violation{std::move(error)};
  case Server_errc::c53_insufficient_resources:
    throw c53_Insufficient_resources{std::move(error)};
  case Server_errc::c53_disk_full:
    throw c53_Disk_full{std::move(error)};
  case Server_errc::c53_out_of_memory:
    throw c53_Out_of_memory{std::move(error)};
  case Server_errc::c53_too_many_connections:
    throw c53_Too_many_connections{std::move(error)};
  case Server_errc::c53_configuration_limit_exceeded:
    throw c53_Configuration_limit_exceeded{std::move(error)};
  case Server_errc::c54_program_limit_exceeded:
    throw c54_Program_limit_exceeded{std::move(error)};
  case Server_errc::c54_statement_too_complex:
    throw c54_Statement_too_complex{std::move(error)};
  case Server_errc::c54_too_many_columns:
    throw c54_Too_many_columns{std::move(error)};
  case Server_errc::c54_too_many_arguments:
    throw c54_Too_many_arguments{std::move(error)};
  case Server_errc::c55_object_not_in_prerequisite_state:
    throw c55_Object_not_in_prerequisite_state{std::move(error)};
  case Server_errc::c55_object_in_use:
    throw c55_Object_in_use{std::move(error)};
  case Server_errc::c55_cant_change_runtime_param:
    throw c55_Cant_change_runtime_param{std::move(error)};
  case Server_errc::c55_lock_not_available:
    throw c55_Lock_not_available{std::move(error)};
  case Server_errc::c55_unsafe_new_enum_value_usage:
    throw c55_Unsafe_new_enum_value_usage{std::move(error)};
  case Server_errc::c57_operator_intervention:
    throw c57_Operator_intervention{std::move(error)};
  case Server_errc::c57_query_canceled:
    throw c57_Query_canceled{std::move(error)};
  case Server_errc::c57_admin_shutdown:
    throw c57_Admin_shutdown{std::move(error)};
  case Server_errc::c57_crash_shutdown:
    throw c57_Crash_shutdown{std::move(error)};
  case Server_errc::c57_cannot_connect_now:
    throw c57_Cannot_connect_now{std::move(error)};
  case Server_errc::c57_database_dropped:
    throw c57_Database_dropped{std::move(error)};
  case Server_errc::c58_system_error:
    throw c58_System_error{std::move(error)};
  case Server_errc::c58_io_error:
    throw c58_Io_error{std::move(error)};
  case Server_errc::c58_undefined_file:
    throw c58_Undefined_file{std::move(error)};
  case Server_errc::c58_duplicate_file:
    throw c58_Duplicate_file{std::move(error)};
  case Server_errc::c72_snapshot_too_old:
    throw c72_Snapshot_too_old{std::move(error)};
  case Server_errc::cf0_config_file_error:
    throw cf0_Config_file_error{std::move(error)};
  case Server_errc::cf0_lock_file_exists:
    throw cf0_Lock_file_exists{std::move(error)};
  case Server_errc::chv_fdw_error:
    throw chv_Fdw_error{std::move(error)};
  case Server_errc::chv_fdw_column_name_not_found:
    throw chv_Fdw_column_name_not_found{std::move(error)};
  case Server_errc::chv_fdw_dynamic_parameter_value_needed:
    throw chv_Fdw_dynamic_parameter_value_needed{std::move(error)};
  case Server_errc::chv_fdw_function_sequence_error:
    throw chv_Fdw_function_sequence_error{std::move(error)};
  case Server_errc::chv_fdw_inconsistent_descriptor_information:
    throw chv_Fdw_inconsistent_descriptor_information{std::move(error)};
  case Server_errc::chv_fdw_invalid_attribute_value:
    throw chv_Fdw_invalid_attribute_value{std::move(error)};
  case Server_errc::chv_fdw_invalid_column_name:
    throw chv_Fdw_invalid_column_name{std::move(error)};
  case Server_errc::chv_fdw_invalid_column_number:
    throw chv_Fdw_invalid_column_number{std::move(error)};
  case Server_errc::chv_fdw_invalid_data_type:
    throw chv_Fdw_invalid_data_type{std::move(error)};
  case Server_errc::chv_fdw_invalid_data_type_descriptors:
    throw chv_Fdw_invalid_data_type_descriptors{std::move(error)};
  case Server_errc::chv_fdw_invalid_descriptor_field_identifier:
    throw chv_Fdw_invalid_descriptor_field_identifier{std::move(error)};
  case Server_errc::chv_fdw_invalid_handle:
    throw chv_Fdw_invalid_handle{std::move(error)};
  case Server_errc::chv_fdw_invalid_option_index:
    throw chv_Fdw_invalid_option_index{std::move(error)};
  case Server_errc::chv_fdw_invalid_option_name:
    throw chv_Fdw_invalid_option_name{std::move(error)};
  case Server_errc::chv_fdw_invalid_string_length_or_buffer_length:
    throw chv_Fdw_invalid_string_length_or_buffer_length{std::move(error)};
  case Server_errc::chv_fdw_invalid_string_format:
    throw chv_Fdw_invalid_string_format{std::move(error)};
  case Server_errc::chv_fdw_invalid_use_of_null_pointer:
    throw chv_Fdw_invalid_use_of_null_pointer{std::move(error)};
  case Server_errc::chv_fdw_too_many_handles:
    throw chv_Fdw_too_many_handles{std::move(error)};
  case Server_errc::chv_fdw_out_of_memory:
    throw chv_Fdw_out_of_memory{std::move(error)};
  case Server_errc::chv_fdw_no_schemas:
    throw chv_Fdw_no_schemas{std::move(error)};
  case Server_errc::chv_fdw_option_name_not_found:
    throw chv_Fdw_option_name_not_found{std::move(error)};
  case Server_errc::chv_fdw_reply_handle:
    throw chv_Fdw_reply_handle{std::move(error)};
  case Server_errc::chv_fdw_schema_not_found:
    throw chv_Fdw_schema_not_found{std::move(error)};
  case Server_errc::chv_fdw_table_not_found:
    throw chv_Fdw_table_not_found{std::move(error)};
  case Server_errc::chv_fdw_unable_to_create_execution:
    throw chv_Fdw_unable_to_create_execution{std::move(error)};
  case Server_errc::chv_fdw_unable_to_create_reply:
    throw chv_Fdw_unable_to_create_reply{std::move(error)};
  case Server_errc::chv_fdw_unable_to_establish_connection:
    throw chv_Fdw_unable_to_establish_connection{std::move(error)};
  case Server_errc::cp0_plpgsql_error:
    throw cp0_Plpgsql_error{std::move(error)};
  case Server_errc::cp0_raise_exception:
    throw cp0_Raise_exception{std::move(error)};
  case Server_errc::cp0_no_data_found:
    throw cp0_No_data_found{std::move(error)};
  case Server_errc::cp0_too_many_rows:
    throw cp0_Too_many_rows{std::move(error)};
  case Server_errc::cp0_assert_failure:
    throw cp0_Assert_failure{std::move(error)};
  case Server_errc::cxx_internal_error:
    throw cxx_Internal_error{std::move(error)};
  case Server_errc::cxx_data_corrupted:
    throw cxx_Data_corrupted{std::move(error)};
  case Server_errc::cxx_index_corrupted:
    throw cxx_Index_corrupted{std::move(error)};
  }
}

} // namespace dmitigr::pgfe
